apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nestjs-app-dev

resources:
  - ../../base

patches:
  - path: patches/deployment-patch.yaml

configMapGenerator:
  - name: nestjs-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - SWAGGER_ENABLED=true
replicas:
  - name: nestjs-app
    count: 3
