apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nestjs-app-dev

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: ducdt1999/nestjs-app
    newTag: dev
