apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ducdt1999/my-nestjs-app.git
    targetRevision: master
    path: kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: nestjs-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
