apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YourUsername/my-nest-app.git
    targetRevision: development
    path: kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nestjs-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
