# Build stage
FROM --platform=linux/amd64 node:18-alpine AS build
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install
COPY . .
RUN pnpm build

# Production stage
FROM --platform=linux/amd64 node:18-alpine
WORKDIR /app
COPY --from=build /app/package.json /app/pnpm-lock.yaml ./
COPY --from=build /app/dist ./dist
RUN npm install -g pnpm && pnpm install --prod

EXPOSE 3000
CMD ["node", "dist/main.js"]