apiVersion: v1
kind: Secret
metadata:
  name: repo-github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ducdt1999/my-nestjs-app.git
  username: ducdt1999
  password: your-github-personal-access-token
