name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - production
  pull_request:
    branches:
      - development
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

  build-and-push:
    needs: build-and-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Docker login
        run: |
          echo "Docker login step completed"
          echo "Using username: ${{ secrets.DOCKERHUB_USERNAME != '' && 'Username is set' || 'Username is NOT set' }}"
          echo "Using token: ${{ secrets.DOCKERHUB_TOKEN != '' && 'Token is set' || 'Token is NOT set' }}"

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set environment variables based on branch
        run: |
          if [ "${{ env.BRANCH_NAME }}" = "development" ]; then
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "TAG=dev" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" = "production" ]; then
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "TAG=prod" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ducdt1999/nestjs-app:${{ env.TAG }}
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
          cache-from: type=registry,ref=ducdt1999/nestjs-app:${{ env.TAG }}
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set environment variables based on branch
        run: |
          if [ "${{ env.BRANCH_NAME }}" = "development" ]; then
            echo "APP_NAME=nestjs-app-dev" >> $GITHUB_ENV
            echo "NAMESPACE=nestjs-app-dev" >> $GITHUB_ENV
            echo "TAG=dev" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" = "production" ]; then
            echo "APP_NAME=nestjs-app-prod" >> $GITHUB_ENV
            echo "NAMESPACE=nestjs-app" >> $GITHUB_ENV
            echo "TAG=prod" >> $GITHUB_ENV
          fi

      - name: Debug Environment Variables
        run: |
          echo "APP_NAME: ${{ env.APP_NAME }}"
          echo "NAMESPACE: ${{ env.NAMESPACE }}"
          echo "BRANCH_NAME: ${{ env.BRANCH_NAME }}"
          echo "TAG: ${{ env.TAG }}"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Debug Kubernetes Configuration Before
        run: |
          echo "Current KUBECONFIG: $KUBECONFIG"
          kubectl config view || echo "No kubectl config found"
          echo "Current HOME directory: $HOME"
          ls -la ~/.kube || echo "No .kube directory"

      - name: Check KUBE_CONFIG secret
        run: |
          # Kiểm tra xem secret KUBE_CONFIG có tồn tại không
          if [ -z "${{ secrets.KUBE_CONFIG }}" ]; then
            echo "ERROR: KUBE_CONFIG secret is empty or not set!"
            exit 1
          fi

          # Kiểm tra độ dài của secret
          CONFIG_LENGTH=$(echo "${{ secrets.KUBE_CONFIG }}" | wc -c)
          echo "KUBE_CONFIG length: $CONFIG_LENGTH characters"

          # Kiểm tra nếu config có chứa các thành phần cần thiết (không hiển thị toàn bộ nội dung)
          echo "Checking for essential components in KUBE_CONFIG:"
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "apiVersion:" && echo "- apiVersion: Found" || echo "- apiVersion: MISSING!"
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "clusters:" && echo "- clusters: Found" || echo "- clusters: MISSING!"
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "users:" && echo "- users: Found" || echo "- users: MISSING!"
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "contexts:" && echo "- contexts: Found" || echo "- contexts: MISSING!"
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "current-context:" && echo "- current-context: Found" || echo "- current-context: MISSING!"

          # Kiểm tra nếu có token hoặc cert (không hiển thị giá trị cụ thể)
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "token:" && echo "- Authentication token: Found" || echo "- Authentication token: MISSING!"
          echo "${{ secrets.KUBE_CONFIG }}" | grep -q "certificate-authority-data:" && echo "- CA data: Found" || echo "- CA data: Not found (but might not be required)"

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          chmod 600 kubeconfig.yaml
          # Kiểm tra nội dung kubeconfig để đảm bảo hợp lệ
          echo "Kiểm tra nội dung kubeconfig..."
          grep "server:" kubeconfig.yaml || echo "Không tìm thấy thông tin server trong kubeconfig"
          echo "Kiểm tra thông tin xác thực..."
          grep "token:" kubeconfig.yaml || echo "Không tìm thấy token trong kubeconfig"
          echo "Kiểm tra kết nối đến Kubernetes cluster..."
          kubectl --kubeconfig=kubeconfig.yaml get nodes

      - name: Debug Kubernetes Configuration After
        run: |
          echo "Kiểm tra cấu hình kubectl với kubeconfig mới..."
          kubectl --kubeconfig=kubeconfig.yaml config view
          kubectl --kubeconfig=kubeconfig.yaml config current-context
          kubectl --kubeconfig=kubeconfig.yaml cluster-info

      - name: Update Deployment
        run: |
          echo "Checking if namespace exists..."
          kubectl --kubeconfig=kubeconfig.yaml get namespace ${{ env.NAMESPACE }} || kubectl --kubeconfig=kubeconfig.yaml create namespace ${{ env.NAMESPACE }}

          # Tạo hoặc cập nhật DockerHub secret để tránh lỗi ImagePullBackOff
          echo "Tạo Docker registry secret..."
          kubectl --kubeconfig=kubeconfig.yaml create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email=your-email@example.com \
            -n ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl --kubeconfig=kubeconfig.yaml apply -f -

          # Đảm bảo deployment sử dụng secret này
          echo "Patch deployment để sử dụng imagePullSecrets..."
          kubectl --kubeconfig=kubeconfig.yaml patch deployment nestjs-app -n ${{ env.NAMESPACE }} --type=json \
            -p='[{"op": "add", "path": "/spec/template/spec/imagePullSecrets", "value": [{"name": "dockerhub-secret"}]}]' || true

          echo "Checking if deployment exists..."
          if kubectl --kubeconfig=kubeconfig.yaml get deployment nestjs-app -n ${{ env.NAMESPACE }} 2>/dev/null; then
            echo "Updating existing deployment..."
            kubectl --kubeconfig=kubeconfig.yaml set image deployment/nestjs-app nestjs-app=ducdt1999/nestjs-app:${{ env.TAG }} -n ${{ env.NAMESPACE }}
          else
            echo "Creating new deployment from manifest..."
            # Áp dụng file deployment từ repository với kustomize
            kubectl --kubeconfig=kubeconfig.yaml apply -k kubernetes/overlays/${{ env.BRANCH_NAME }} -n ${{ env.NAMESPACE }}
          fi

          # Thêm thời gian ngắn để bắt đầu quá trình rollout
          echo "Chờ khởi tạo pod mới..."
          sleep 10

          # Kiểm tra sự kiện trong namespace để tìm lỗi
          echo "Events trong namespace:"
          kubectl --kubeconfig=kubeconfig.yaml get events -n ${{ env.NAMESPACE }} --sort-by='.lastTimestamp'

          # Kiểm tra trạng thái của các pods
          echo "Chi tiết pods:"
          kubectl --kubeconfig=kubeconfig.yaml get pods -n ${{ env.NAMESPACE }} -o wide

          # Kiểm tra chi tiết về deployment để xem rollout strategy
          echo "Chi tiết về Deployment:"
          kubectl --kubeconfig=kubeconfig.yaml describe deployment nestjs-app -n ${{ env.NAMESPACE }}

          # Kiểm tra các pods đang trong quá trình tạo hoặc terminate
          echo "Pods đang có vấn đề:"
          PODS=$(kubectl --kubeconfig=kubeconfig.yaml get pods -n ${{ env.NAMESPACE }} -l app=nestjs-app -o jsonpath='{.items[*].metadata.name}')
          for POD in $PODS; do
            echo "* Thông tin chi tiết về pod $POD:"
            kubectl --kubeconfig=kubeconfig.yaml describe pod $POD -n ${{ env.NAMESPACE }}
            echo "* Logs của pod $POD:"
            kubectl --kubeconfig=kubeconfig.yaml logs $POD -n ${{ env.NAMESPACE }} || echo "Không thể lấy logs"
          done

          echo "Checking deployment rollout status with increased timeout..."
          kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/nestjs-app -n ${{ env.NAMESPACE }} --timeout=60s || {
            echo "Rollout không hoàn tất trong thời gian chờ. Cố gắng giải quyết vấn đề..."

            # Kiểm tra xem có pods nào bị kẹt trong trạng thái chờ xóa không
            TERMINATING_PODS=$(kubectl --kubeconfig=kubeconfig.yaml get pods -n ${{ env.NAMESPACE }} -l app=nestjs-app --field-selector status.phase=Running -o jsonpath='{.items[*].metadata.deletionTimestamp}')
            if [ -n "$TERMINATING_PODS" ]; then
              echo "Có pods đang bị kẹt trong trạng thái Terminating. Xóa force..."
              for POD in $PODS; do
                kubectl --kubeconfig=kubeconfig.yaml delete pod $POD -n ${{ env.NAMESPACE }} --force --grace-period=0 || true
              done
            fi

            # Thử restart deployment
            echo "Force restart deployment để tạo pods mới..."
            kubectl --kubeconfig=kubeconfig.yaml rollout restart deployment/nestjs-app -n ${{ env.NAMESPACE }}

            # Thêm thời gian để bắt đầu quá trình rollout mới
            echo "Chờ khởi tạo lại pod..."
            sleep 15

            # Kiểm tra lại trạng thái
            echo "Trạng thái pods sau khi restart:"
            kubectl --kubeconfig=kubeconfig.yaml get pods -n ${{ env.NAMESPACE }} -l app=nestjs-app
          }

          echo "Deployment information:"
          kubectl --kubeconfig=kubeconfig.yaml get deployment nestjs-app -n ${{ env.NAMESPACE }} -o wide
          kubectl --kubeconfig=kubeconfig.yaml get pods -n ${{ env.NAMESPACE }} -l app=nestjs-app
